import streamlit as st
import subprocess
import os
import sys
import glob

st.set_page_config(
    page_title="PN Automation Dashboard",
    layout="wide"
)

st.title("PN Automation Dashboard")

uploaded_file = st.file_uploader(
    "Upload Raw File",
    type=["xlsx"]
)

if uploaded_file:

    # Save uploaded file using original filename
    uploaded_path = os.path.basename(uploaded_file.name)

    with open(uploaded_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    st.success("File uploaded successfully")

    if st.button("Run Automation"):

        # Remove old output files
        for file in glob.glob("*_Analysis.xlsx"):
            try:
                os.remove(file)
            except OSError:
                pass

        for file in glob.glob("*_Analysis.csv"):
            try:
                os.remove(file)
            except OSError:
                pass

        with st.spinner("Running Automation..."):

            result = subprocess.run(
                [sys.executable, "pn.py", uploaded_path],
                capture_output=True,
                text=True
            )

        # Show any errors
        if result.returncode != 0:
            st.error("Automation Failed")
            st.code(result.stderr)
            st.stop()

        # Show logs if any
        if result.stdout:
            st.code(result.stdout)

        # Output filename generated by pn.py
        output_file = uploaded_path.replace(
            ".xlsx",
            "_Analysis.xlsx"
        )

        if os.path.exists(output_file):

            st.success("Report Generated Successfully")

            with open(output_file, "rb") as f:
                report_bytes = f.read()

            st.download_button(
                label="📥 Download Report",
                data=report_bytes,
                file_name=os.path.basename(output_file),
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

        else:

            st.error(
                f"Output file not found: {output_file}"
            )
